services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8082
    volumes:
      - /volume1/docker/qbittorrent/config:/config
      - /volume1/Movies/Media/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8082:8082
    restart: unless-stopped
    networks:
      - internal
    ##use public ip or local ip first dont use reverse proxy. And disable CSRF protection.
