services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: bridge
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Aisa/Kolkata
      - WEBUI_PORT=8082
    volumes:
      - /qbittorrent/config:/config
      - /volume1/Movies/Media/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8082:8082
    restart: unless-stopped
    ##use public ip or local ip first dont use reverse proxy. And disable CSRF protection.
