services:
  jdownloader-2:
    container_name: jdownloader-2
    network_mode: bridge
    image: jlesage/jdownloader-2:latest
    ports:
      - 5800:5800
    volumes:
      - /volume1/docker/jdownloader2/config:/config:rw
      - /volume1/docker/jdownloader2/downloads:/output:rw
    env_file:
      - /data/secret.env
   # environment: 
   #   MYJD_USER: email@email.com #from the myjdownloader.org free account 
   #   MYJD_PASSWORD: password
