services:
  jdownloader-2:
    container_name: jdownloader-2
    network_mode: bridge
    image: jlesage/jdownloader-2:latest
    ports:
      - 5800:5800
    volumes:
      - /volume1/docker/jdownloader2/config:/config:rw
      - /volume1/docker/jdownloader2/downloads:/output:rw
    env_file:
      - /data/secret.env
    environment: 
      #MYJDOWNLOADER_EMAIL: email@email.com #from the myjdownloader.org free account 
      #MYJDOWNLOADER_PASSWORD: password
      #MYJDOWNLOADER_DEVICE_NAME: name
      #WEB_AUTHENTICATION_USERNAME: email@email.com
      #WEB_AUTHENTICATION_PASSWORD: password
      SECURE_CONNECTION: 1
      WEB_AUTHENTICATION: 1
