version: '3'
services:
  jdownloader-2:
    container_name: jdownloader-2
    network_mode: bridge
    image: daniel0076/jdownloader-2:latest
    ports:
      - 5800:5800
    volumes:
      - /jdownloader2/config:/config:rw
      - /Media:/output:rw
    env_file:
      - secret.env
   # environment: 
   #   MYJD_USER: email@email.com #from the myjdownloader.org free account 
   #   MYJD_PASSWORD: password
