version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /NextCloud/postgress:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
        
  app:
    image: nextcloud
    restart: always
    env_file:
      - /data/secret.env
    ports:
      - 8090:80
    volumes:
      - /NextCloud/nextcloud:/var/www/html
      - /Media:/mnt/data/d1
      #execute below script to get full access on external local storage
      #sudo chown -R www-data:www-data /Media
      #sudo chmod -R 0750 /Media
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
      #- NEXTCLOUD_ADMIN_USER=username
      #- NEXTCLOUD_ADMIN_PASSWORD=password
      - TRUSTED_PROXIES=swag
      - OVERWRITEPROTOCOL=https
      #- OVERWRITECLIURL=https://nextcloud.domainname
      #- OVERWRITEHOST=nextcloud.domainname
      #- NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.domainname

    depends_on:
      - db
      
