networks:
    internal:
      external: true
      
services:
  postgres:
    image: postgres
    container_name: nextcloud-postgres
    restart: always
    volumes:
      - /volume1/docker/nextcloud/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Kolkata
    networks:
      - internal
        
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    env_file:
      - /data/secret.env
    #ports:
    #  - 8090:80
    volumes:
      - /volume1/docker/nextcloud/data:/var/www/html
      - /volume1/homes:/mnt/data/d1
      - /etc/localtime:/etc/localtime:ro
      #execute below script to get full access on external local storage
      #sudo chown -R www-data:www-data /Media
      #sudo chmod -R 0750 /Media
      #else execute this line alone for the folder
      #sudo chmod -R 777 /Media
    environment:
      - TZ=Asia/Kolkata
      - POSTGRES_HOST=nextcloud-postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- NEXTCLOUD_ADMIN_USER=username
      #- NEXTCLOUD_ADMIN_PASSWORD=password
      #- TRUSTED_PROXIES=swag
      #- OVERWRITEPROTOCOL=https
      #- OVERWRITECLIURL=https://nextcloud.domainname
      #- OVERWRITEHOST=nextcloud.domainname
      #- NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.domainname
    depends_on:
      - postgres
    networks:
      - internal
      
  cron:
    image: nextcloud
    container_name: nextcloud-cron
    restart: always
    volumes:
      - /volume1/docker/nextcloud/data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /cron.sh
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      - postgres
      - nextcloud  
    networks:
      - internal
      
