networks:
    internal:
      external: true
      
services:     

  server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik
    restart: unless-stopped
    command: server
    env_file:
      - /data/secret.env #Portainer data folder
    environment:
      TZ: Asia/Kolkata
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      #AUTHENTIK_POSTGRESQL__PASSWORD: authentik
      #AUTHENTIK_SECRET_KEY: authentikn
      #AUTHENTIK_BOOTSTRAP_PASSWORD: authentik
      AUTHENTIK_LOG_LEVEL: warning
      COMPOSE_PORT_HTTP: 80
      COMPOSE_PORT_HTTPS: 443
    volumes:
      - /volume1/docker/authentik/data/media:/media
      - /volume1/docker/authentik/data/templates:/templates
      - /etc/localtime:/etc/localtime:ro
    #ports:
    #  - "9010:9000"
    #  - "9011:9443"
    depends_on:
      - authentik-postgresql
      - authentik-redis
    networks:
      - internal
      
  worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    env_file:
      - /data/secret.env #Portainer data folder
    environment:
      TZ: Asia/Kolkata
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      #AUTHENTIK_POSTGRESQL__PASSWORD: authentik
      #AUTHENTIK_SECRET_KEY: authentik
      #AUTHENTIK_BOOTSTRAP_PASSWORD: authentik
      AUTHENTIK_LOG_LEVEL: warning
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/authentik/data/certs:/certs
      - /volume1/docker/authentik/data/media:/media
      - /volume1/docker/authentik/data/templates:/templates
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - authentik-postgresql
      - authentik-redis
    networks:
      - internal

  ldap:
    image: ghcr.io/goauthentik/ldap:latest
    container_name: authentik-ldap
    restart: unless-stopped
    ports:
    - 389:3389
    - 636:6636
    env_file:
      - /data/secret.env #Portainer data folder
    networks:
      - internal
    depends_on:
      - server
    #environment:
      #AUTHENTIK_HOST: https://your-authentik.tld
      #AUTHENTIK_INSECURE: "false"
      #AUTHENTIK_TOKEN: token-generated-by-authentik

      
  authentik-postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: authentik-postgresql
    restart: unless-stopped
    volumes:
      - /volume1/docker/authentik/db:/var/lib/postgresql/data
    env_file:
      - /data/secret.env #Portainer data folder
    environment:
      #POSTGRES_PASSWORD: authentik
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
    networks:
      - internal
      
  authentik-redis:
    image: docker.io/library/redis:alpine
    container_name: authentik-redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - /volume1/docker/authentik/redis:/data
    networks:
      - internal

#echo "AUTHENTIK_PG_PASS=$(openssl rand -base64 36 | tr -d '\n')" >> .env
#echo "AUTHENTIK_SECRET_KEY=$(openssl rand -base64 60 | tr -d '\n')" >> .env
#echo "AUTHENTIK_BOOTSTRAP_PASSWORD=$(openssl rand -base64 36 | tr -d '\n')" >> .env
