services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - LOG_LEVEL=info
    network_mode: bridge
    ports:
      - 3001:3000
    volumes:
      - /volume1/docker/homepage/config:/app/config
      - /volume1/docker/homepage/images:/app/images  
      - /volume1/docker/homepage/icons:/app/icons  
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
