services:
  mediafusion:
    image: mhdzumair/mediafusion:4.3.33
    container_name: mediafusion
    command: >
      sh -c "sed -i
      's|https://raw.githubusercontent.com/mhdzumair/MediaFusion/main/resources/json/scraper_config.json|https://raw.githubusercontent.com/kesavananbu/MediaFusion/main/resources/json/scraper_config.json|g' /mediafusion/db/config.py
      && echo '==== FILE CONTENTS AFTER REPLACE ===='
      && cat /mediafusion/db/config.py
      && /mediafusion/deployment/startup.sh"
    env_file:
      - /data/secret.env #Portainer data folder
    environment:
      #- SECRET_KEY=secret_key
      #- API_PASSWORD=app_password
      - HOST_URL=http://mediafusion:8000
      - POSTER_HOST_URL=http://mediafusion:8000
      - FLARESOLVERR_HOST=http://flaresolverr:8191
      #- MONGO_URI=mongodb://mongodb:27017/mediafusion
      - REDIS_URL=redis://redis:6379
      - ENABLE_RATE_LIMIT=false
      - is_scrap_from_mediafusion=False
      - is_scrap_from_zilean=False
      - is_scrap_from_prowlarr=False
      - is_scrap_from_bt4g=False
      - store_stremthru_magnet_cache=False
      - disable_tamil_blasters_scheduler=False
      - disable_tamilmv_scheduler=False
      - disable_tamilultra_scheduler=False
      - disable_sport_video_scheduler=True
      - disable_arab_torrents_scheduler=True
      - disable_dlhd_scheduler=True
      - cleanup_expired_scraper_task_crontab=0 * * * *
      - cleanup_expired_cache_task_crontab=0 * * * *
      - tamil_blasters_scheduler_crontab=0 * * * *
      - tamilmv_scheduler_crontab=20 * * * *
      - tamilultra_scheduler_crontab=40 * * * *
    depends_on:
      #- mongodb
      - redis
      - dramatiq-worker
    restart: unless-stopped
    networks:
      - internal

  dramatiq-worker:
    image: mhdzumair/mediafusion:4.3.33
    container_name: mediafusion-worker
    #command: ["dramatiq", "api.task", "-p", "1", "-t", "4"]
    command: >
      sh -c "sed -i
      's|https://raw.githubusercontent.com/mhdzumair/MediaFusion/main/resources/json/scraper_config.json|https://raw.githubusercontent.com/kesavananbu/MediaFusion/main/resources/json/scraper_config.json|g' /mediafusion/db/config.py
      && echo '==== FILE CONTENTS AFTER REPLACE ===='
      && cat /mediafusion/db/config.py
      && dramatiq api.task -p 1 -t 4"
    env_file:
      - /data/secret.env #Portainer data folder
    environment:
      #- SECRET_KEY=secret_key
      #- API_PASSWORD=app_password
      - HOST_URL=http://mediafusion:8000
      - POSTER_HOST_URL=http://mediafusion:8000
      - FLARESOLVERR_HOST=http://flaresolverr:8191
      #- MONGO_URI=mongodb://mongodb:27017/mediafusion
      - REDIS_URL=redis://redis:6379
      - ENABLE_RATE_LIMIT=false
      - is_scrap_from_mediafusion=False
      - is_scrap_from_zilean=False
      - is_scrap_from_prowlarr=False
      - is_scrap_from_bt4g=False
      - store_stremthru_magnet_cache=False
      - disable_tamil_blasters_scheduler=False
      - disable_tamilmv_scheduler=False
      - disable_tamilultra_scheduler=False
      - disable_sport_video_scheduler=True
      - disable_arab_torrents_scheduler=True
      - disable_dlhd_scheduler=True
      - cleanup_expired_scraper_task_crontab=0 * * * *
      - cleanup_expired_cache_task_crontab=0 * * * *
      - tamil_blasters_scheduler_crontab=0 * * * *
      - tamilmv_scheduler_crontab=20 * * * *
      - tamilultra_scheduler_crontab=40 * * * *
    depends_on:
      #- mongodb
      - redis
    restart: unless-stopped
    networks:
      - internal

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    networks:
      - internal

  browserless:
    image: ghcr.io/browserless/chromium
    container_name: browserless
    environment:
      - TIMEOUT=-1
    restart: unless-stopped
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - /volume1/docker/mediafusion/redis:/data
    command: redis-server --appendonly yes --save 60 1
    restart: unless-stopped
    networks:
      - internal

#Commented out using mongodb cloud db certain features required latest version. Local Machine not comptaible to support mongodb latest.
#mongodb:
#  image: mongo:4.4.29
#  container_name: mongodb
#  volumes:
#    - /volume1/docker/mediafusion/mongo:/data/db
#  restart: unless-stopped
#  networks:
#    - mediafusion_network

networks:
    internal:
      external: true
