
services:
    adguard-home:
        container_name: adguard-home
        image: adguard/adguardhome:latest
        #network_mode: bridge
        network_mode: host
        # modify the https port and http port in the config file
        # 443 -> 4444, 80 -> 8080
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        environment:
            TZ: Asia/Kolkata
        volumes:
            - /volume1/docker/AdGuardData/workdir:/opt/adguardhome/work
            - /volume1/docker/AdGuardData/confdir:/opt/adguardhome/conf
            - /volume1/docker/AdGuardData/certdir:/opt/adguardhome/cert # For SSL Certificates path
            - /etc/localtime:/etc/localtime:ro
            - /etc/TZ:/etc/timezone:ro
            - /etc/hosts:/etc/hosts:ro
        #ports:
        #    - 53:53/tcp
        #    - 53:53/udp
        #    - 8080:80/tcp
        #    - 8080:80/udp
        #    - 442:443/tcp
        #    - 442:443/udp
        #    - 853:853/tcp
        #    - 853:853/udp
        #    - 5443:5443/tcp
        #    - 5443:5443/udp
        #    - 784:784/tcp
        #    - 784:784/udp
        #    - 3001:3000/tcp
        #    - 3001:3000/udp


# hostsfile_enabled: true Add this in config field
