networks:
    internal:
      external: true

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /volume1/docker/jellyfin/config:/config
      - /volume1/Movies/cache:/cache
      - /volume1/Movies/Series:/data/tvshows
      - /volume1/Movies/Media:/data/movies #:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - internal
    devices: #include only if you have intel/amd gpu
      - /dev/dri/:/dev/dri/
      #- /dev/dri/renderD128:/dev/dri/renderD128
      #- /dev/dri/card0:/dev/dri/card0
    #ports:
    #  - 8096:8096
    #user: "${UID}:${GID}"
    #network_mode: bridge

