services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: "${UID}:${GID}"
    network_mode: bridge
    volumes:
      - /volume1/docker/jellyfin/config:/config
      - /volume1/Movies/cache:/cache
      - /volume1/Movies/Media:/media #:ro
    ports:
      - 8096:8096
    restart: unless-stopped
