version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "${UID}:${GID}"
    network_mode: bridge
    volumes:
      - /jellyfin/config:/config
      - /Media/cache:/cache
      - /Media:/media:ro
    ports:
      - 8096:8096
    restart: unless-stopped
