services:
  proxy-manager:
    container_name: proxy-manager
    image: jc21/nginx-proxy-manager:latest
    network_mode: bridge
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxymanager_data:/data
      - proxymanager_letsencrypt:/etc/letsencrypt

volumes:
  proxymanager_data:
  proxymanager_letsencrypt:
