services:
  proxy-manager:
    container_name: proxy-manager
    image: jc21/nginx-proxy-manager:latest
    network_mode: host
    restart: unless-stopped
    #ports:
    #  - '80:80'
    #  - '81:81'
    #  - '443:443'
    volumes:
      - /volume1/docker/proxymanager/data:/data
      - /volume1/docker/proxymanager/letsencrypt:/etc/letsencrypt
