services:
  proxy-manager:
    container_name: proxy-manager
    image: jc21/nginx-proxy-manager:latest
    network_mode: host
    restart: unless-stopped
    #ports:
    #  - '80:80'
    #  - '81:81'
    #  - '443:443'
    volumes:
      - /volume1/docker/proxymanager/data:/data
      - /volume1/docker/proxymanager/letsencrypt:/etc/letsencrypt
      - /volume1/docker/ssl_certs/customdeployhook_nginx:/etc/letsencrypt/renewal-hooks/deploy
      #Advanced global config setup for authentik domain level forward proxy
      #Replace the _access.conf file which used to generate the access list
      - /volume1/docker/proxymanager/custom/server_proxy.conf:/data/nginx/custom/server_proxy.conf
      - /volume1/docker/proxymanager/custom/custom_access.conf:/app/templates/_access.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
    environment:
      TZ: Asia/Kolkata
