services:
  proxy-manager:
    container_name: proxy-manager
    image: jc21/nginx-proxy-manager:latest
    network_mode: host
    restart: unless-stopped
    #ports:
    #  - '80:80'
    #  - '81:81'
    #  - '443:443'
    volumes:
      - /volume1/docker/proxymanager/data:/data
      - /volume1/docker/proxymanager/letsencrypt:/etc/letsencrypt
      - /volume1/docker/proxymanager/global_rule/server_proxy.conf:/data/nginx/custom/server_proxy.conf
      - /volume1/docker/proxymanager/global_rule/custom_access.conf:/app/templates/_access.conf:ro
