services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
    networks:
      - internal
    #ports:
    #  - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/dockhand/data:/app/data
    devices: #include only if you have intel/amd gpu
      - /dev/dri/:/dev/dri/


networks:
    internal:
      external: true
